### PR TITLE
fix(get-package-name): resolve paths properly before matching

### LINKED ISSUE #44: Local template packages only work from relative paths
# 🐞 Bug Report

## Describe the bug

When running a local template for testing purposes, the path to the template only works if it is relative to the current directory. Absolute paths give an error.

## To Reproduce

1. Run `npm pack` in a template directory to create a tgz file.
2. Run `npm init using-template /Users/me/workspace/some-template/some-template-1.0.0.tgz`
3. Get error.
```
Failed to create module: Invalid or unexpected token
/Users/me/workspace/some-template/some-template-1.0.0.tgz:1
�
^
SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
```

OTOH, if you pass a relative path to tgz from the current directory, it works as expected.
```
npm init using-template ../some-template/some-template-1.0.0.tgz`
```

## Expected behavior

There should be no difference between absolute and relative paths.

## System information

- OS: macOS
- Version of create-using-template: v1.11.0
- Node version: v18.18.2

### PR DESCRIPTION
**Pull request by smackfu**
The current logic for local template packages is:
1. Install the template package, 
2. Look up the template module name via the template package path using the package.json. 

This seems to only work properly when the local template package filename is in the form `./some/path/package.tgz`.  If the filename is an absolute path, it doesn't match and errors out.  If the filename is a relative path but uses `..` to go up the tree, it doesn't match and errors.  I believe it only works in the one case because the "." in the filename is parsed as a regex and matches any character.

This PR changes the logic to fully resolve both the filename in the package.json and the filename passed on the command line, then directly compare them.  This should work reliably for all path values.

It also removes the logic that only resolves the path to the tar.gz file when it's a relative path.  This isn't needed since the check if the file exists is more reliable and general. This fixes the case where you do not provide a path at all, for instance: `npm init using-template some-template-template-1.0.0.tgz`

Fixes #44

### CODE REVIEW

**Review by 10xLaCroixDrinker — APPROVED** [review]

File: src/utils/get-package-name.js [hunk 1]
```diff
@@ -17,10 +17,17 @@ const path = require('path');
...
 const getPackageName = (templateName) => {
-  if (templateName.match(/^\..+\.(tgz|tar(\.gz){0,1})$/)) {
+  if (templateName.match(/.+\.(tgz|tar(\.gz){0,1})$/)) {
+    const templatePath = path.resolve(templateName);
     const { dependencies } = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../package.json')));
     return Object.entries(dependencies)
-      .find(([, version]) => version.match(templateName))[0];
+      .find(([, version]) => {
+        if (version.startsWith('file:')) {
+          const dependencyPath = path.resolve(__dirname, '../../', version.slice(5));
```
Comment (giulianok) [inline src/utils/get-package-name.js:26]: curious, since it's hard to visualize, why `../../` and not `../` or `../../../`

Comment (smackfu) [reply src/utils/get-package-name.js:26]: If I remember correctly, `__dirname` is the current javascript file's dir, so `../../` is reversing out `src/utils` to get back to the directory where the package.json is.  Then the path stored in the package.json with the "file:" prefix is a relative path from that directory.

**Review by JAdshead — APPROVED** [review]
